services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client/dist:/app/client/dist
    environment:
      - NODE_ENV=${NODE_ENV}
    command: pnpm --filter client run build

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email minjungw00@naver.com --agree-tos --no-eff-email -d nocta.site -d www.nocta.site

volumes:
  certbot-etc:

networks:
  app-network:
    driver: bridge
