name: Deploy on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, boost-was] # 라벨에 해당하는 runner로 실행

    steps:
      # 1. 레포지토리 클론
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Docker Compose로 서비스 빌드 및 재시작
      - name: Build and Deploy Docker Images
        env:
          NODE_ENV: production
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          docker-compose up -d --build

      # 3. Clean up Old Images
      - name: Remove Dangling Images
        run: docker image prune -f
