name: Lint and Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint_and_unit_test:
    name: Lint and Unit Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      # Run lint
      - name: Run Lint
        run: pnpm eslint .

      # Run Unit tests
      - name: Run Unit Tests
        run: pnpm test

  test_building_docker_image:
    name: Test Building Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Test Building Docker Images
      - name: Test Building Docker Images
        env:
          NODE_ENV: production
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          docker-compose build
